### ISSUE TITLE
Timer Component

### ISSUE THREAD

**Issue by huntercaron** [ysdn2018/the-next-base#1]
Looking for someone to create a timer component for countdowns on the teaser site.
Should be able to customize the date counting down to in the props.

Something like [Moment](https://momentjs.com/) might come in handy. If you wanna use it just `yarn add Moment`. 

Just create it in the 'src/components' directory.

Thanks a bunch 👽

**Comment by huntercaron** [comment]
actually @kowalskijohn could you do this?

**Comment by kowalskijohn** [comment]
@huntercaron gotchu fam. will work on and hopefully finish tomorrow.

**Comment by huntercaron** [comment]
@kowalskijohn sweet ty
